import style from "../styles/mobile.module.css";
import Link from "next/link";
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Footer from '../componenet/Footer'
import Main from '../componenet/Main'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const makeVisible = () => {
    const sidebar = document.getElementById("sidebar");
    const centere = document.getElementById("centere");
    if(centere) {
      centere.style.display = "none"
    }
    if (sidebar) {
      sidebar.style.display = "flex";
    }
  }
  const makeInvisible = () => {
    const centere = document.getElementById("centere");
    if(centere) {
      centere.style.display = "flex"
    }
    const sidebar = document.getElementById("sidebar");
    if (sidebar) {
      sidebar.style.display = "none";
    }

  }

  return (
    <>
      <Head>
        <title>Leading Bright</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/rel.png" />
      </Head>
      <main className={styles.main}>
        <nav className={style.navsele} onClick={makeVisible}>
          <div style={{ width: "1.7rem", height: "1.3rem", backgroundColor: "gray" }}>
          <Image alt='Home' src="/home.svg" width="25" height="17" />
          {/* <h2>---</h2> */}
          </div>
          <div style={{ width: "5rem", height: "5rem", backgroundColor: "transparent" }} onClick={makeVisible}></div>
        </nav>
        <div id="sidebar" className={style.pcdisapp}>
          <div className={style.sideBox}>
            <div style={{ color: "blueviolet" , cursor:"pointer" }} onClick={makeInvisible}>
              <h2>---</h2>
              <h2>--</h2>
              <h2>---</h2>
            </div>
            <h3 style={{marginTop:"2rem" ,fontSize: "1.6em",color: "blue"}}>Leading Code</h3>
            <div className={style.navigation}>
            <Link href="/"><div><Image alt='Home' src="/home.svg" width="25" height="17" />Home</div></Link>
              <Link href="/blog"><div>Blogs</div></Link>
              <Link href="/projects"><div>Projects</div></Link>
              <Link href="/about"><div>About</div></Link>
              <Link href="/contact"><div><Image alt='Home' src="/contact.svg" width="25" height="17" />Contact</div></Link>
            </div>
          </div>
        </div>
        <div className={styles.transparent}>
          <div id="centere" className={styles.center}>
            <h2>Let's Learn JavaScript Together</h2>
            <button><a target="_blank" href="https://www.youtube.com/@leadingbright2580">Leading Bright With Code</a></button>
          </div>
        </div>
      </main>
      <Main />
      <Footer />
    </>
  )
}
